# Generated by Django 2.2.1 on 2019-06-05 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_document_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='description',
            new_name='title',
        ),
    ]
