# Generated by Django 2.2.1 on 2019-06-11 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20190605_0413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='email',
            field=models.EmailField(max_length=255),
        ),
    ]
